# Generated by Django 5.1.3 on 2024-11-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=40)),
                ('userpassword', models.CharField(max_length=40)),
                ('useremail', models.CharField(max_length=40)),
            ],
        ),
    ]
